import { ConstantBase } from "./ConstantBase";

export class PrefectureIdConstant extends ConstantBase {}

export const PrefectureId = {
  HOKKAIDO: new PrefectureIdConstant(1, "北海道"),
  AOMORI: new PrefectureIdConstant(2, "青森県"),
  IWATE: new PrefectureIdConstant(3, "岩手県"),
  MIYAGI: new PrefectureIdConstant(4, "宮城県"),
  AKITA: new PrefectureIdConstant(5, "秋田県"),
  YAMAGATA: new PrefectureIdConstant(6, "山形県"),
  FUKUSHIMA: new PrefectureIdConstant(7, "福島県"),
  IBARAKI: new PrefectureIdConstant(8, "茨城県"),
  TOCHIGI: new PrefectureIdConstant(9, "栃木県"),
  GUMMA: new PrefectureIdConstant(10, "群馬県"),
  SAITAMA: new PrefectureIdConstant(11, "埼玉県"),
  CHIBA: new PrefectureIdConstant(12, "千葉県"),
  TOKYO: new PrefectureIdConstant(13, "東京都"),
  KANAGAWA: new PrefectureIdConstant(14, "神奈川県"),
  NIIGATA: new PrefectureIdConstant(15, "新潟県"),
  TOYAMA: new PrefectureIdConstant(16, "富山県"),
  ISHIKAWA: new PrefectureIdConstant(17, "石川県"),
  FUKUI: new PrefectureIdConstant(18, "福井県"),
  YAMANASHI: new PrefectureIdConstant(19, "山梨県"),
  NAGANO: new PrefectureIdConstant(20, "長野県"),
  GIFU: new PrefectureIdConstant(21, "岐阜県"),
  SHIZUOKA: new PrefectureIdConstant(22, "静岡県"),
  AICHI: new PrefectureIdConstant(23, "愛知県"),
  MIE: new PrefectureIdConstant(24, "三重県"),
  SHIGA: new PrefectureIdConstant(25, "滋賀県"),
  KYOTO: new PrefectureIdConstant(26, "京都府"),
  OSAKA: new PrefectureIdConstant(27, "大阪府"),
  HYOGO: new PrefectureIdConstant(28, "兵庫県"),
  NARA: new PrefectureIdConstant(29, "奈良県"),
  WAKAYAMA: new PrefectureIdConstant(30, "和歌山県"),
  TOTTORI: new PrefectureIdConstant(31, "鳥取県"),
  SHIMANE: new PrefectureIdConstant(32, "島根県"),
  OKAYAMA: new PrefectureIdConstant(33, "岡山県"),
  HIROSHIMA: new PrefectureIdConstant(34, "広島県"),
  YAMAGUCHI: new PrefectureIdConstant(35, "山口県"),
  TOKUSHIMA: new PrefectureIdConstant(36, "徳島県"),
  KAGAWA: new PrefectureIdConstant(37, "香川県"),
  EHIME: new PrefectureIdConstant(38, "愛媛県"),
  KOCHI: new PrefectureIdConstant(39, "高知県"),
  FUKUOKA: new PrefectureIdConstant(40, "福岡県"),
  SAGA: new PrefectureIdConstant(41, "佐賀県"),
  NAGASAKI: new PrefectureIdConstant(42, "長崎県"),
  KUMAMOTO: new PrefectureIdConstant(43, "熊本県"),
  OITA: new PrefectureIdConstant(44, "大分県"),
  MIYAZAKI: new PrefectureIdConstant(45, "宮崎県"),
  KAGOSHIMA: new PrefectureIdConstant(46, "鹿児島県"),
  OKINAWA: new PrefectureIdConstant(47, "沖縄県"),
  getNameByCode: (code: number | null): string => {
    return <string>codeNameMap.get(code);
  },
};

export const PrefectureIdList = [
  new PrefectureIdConstant(1, "北海道"),
  new PrefectureIdConstant(2, "青森"),
  new PrefectureIdConstant(3, "岩手"),
  new PrefectureIdConstant(4, "宮城"),
  new PrefectureIdConstant(5, "秋田"),
  new PrefectureIdConstant(6, "山形"),
  new PrefectureIdConstant(7, "福島県"),
  new PrefectureIdConstant(8, "茨城県"),
  new PrefectureIdConstant(9, "栃木県"),
  new PrefectureIdConstant(10, "群馬県"),
  new PrefectureIdConstant(11, "埼玉県"),
  new PrefectureIdConstant(12, "千葉県"),
  new PrefectureIdConstant(13, "東京都"),
  new PrefectureIdConstant(14, "神奈川県"),
  new PrefectureIdConstant(15, "新潟県"),
  new PrefectureIdConstant(16, "富山県"),
  new PrefectureIdConstant(17, "石川県"),
  new PrefectureIdConstant(18, "福井県"),
  new PrefectureIdConstant(19, "山梨県"),
  new PrefectureIdConstant(20, "長野県"),
  new PrefectureIdConstant(21, "岐阜県"),
  new PrefectureIdConstant(22, "静岡県"),
  new PrefectureIdConstant(23, "愛知県"),
  new PrefectureIdConstant(24, "三重県"),
  new PrefectureIdConstant(25, "滋賀県"),
  new PrefectureIdConstant(26, "京都府"),
  new PrefectureIdConstant(27, "大阪府"),
  new PrefectureIdConstant(28, "兵庫県"),
  new PrefectureIdConstant(29, "奈良県"),
  new PrefectureIdConstant(30, "和歌山県"),
  new PrefectureIdConstant(31, "鳥取県"),
  new PrefectureIdConstant(32, "島根県"),
  new PrefectureIdConstant(33, "岡山県"),
  new PrefectureIdConstant(34, "広島県"),
  new PrefectureIdConstant(35, "山口県"),
  new PrefectureIdConstant(36, "徳島県"),
  new PrefectureIdConstant(37, "香川県"),
  new PrefectureIdConstant(38, "愛媛県"),
  new PrefectureIdConstant(39, "高知県"),
  new PrefectureIdConstant(40, "福岡県"),
  new PrefectureIdConstant(41, "佐賀県"),
  new PrefectureIdConstant(42, "長崎県"),
  new PrefectureIdConstant(43, "熊本県"),
  new PrefectureIdConstant(44, "大分県"),
  new PrefectureIdConstant(45, "宮崎県"),
  new PrefectureIdConstant(46, "鹿児島県"),
  new PrefectureIdConstant(47, "沖縄県"),
];

const codeNameMap = new Map<number | null, string>();
Object.values(PrefectureId).forEach((elem) => {
  if (elem instanceof PrefectureIdConstant) {
    codeNameMap.set(elem.code, elem.name);
  }
});
